#!/bin/sh
# iris doctor — preflight: iris binary, Chrome-family browser, smoke capture.
# Usage: bash scripts/doctor.sh   (exits 0 only if everything works)
set -u

echo "iris-doctor: checking environment…"

# Chrome refuses to run as root without --no-sandbox (crbug.com/638180) and iris
# has no flag to forward it, so wrap the binary in a shim and point iris there.
# Set IRIS_NO_SANDBOX_SHIM=0 to opt out.
iris_chrome_for_iris() {
  real="$1"
  [ "${IRIS_NO_SANDBOX_SHIM:-1}" = "1" ] || { echo "$real"; return 0; }
  [ "$(id -u)" = "0" ] || { echo "$real"; return 0; }
  case "$real" in *chrome-no-sandbox) echo "$real"; return 0 ;; esac
  shim="$HOME/tools/chrome-no-sandbox"
  mkdir -p "$HOME/tools" 2>/dev/null || { echo "$real"; return 0; }
  printf '#!/bin/sh\n# generated by the iris plugin: Chrome will not run as root without --no-sandbox\nexec "%s" --no-sandbox "$@"\n' "$real" > "$shim" 2>/dev/null || { echo "$real"; return 0; }
  chmod +x "$shim" 2>/dev/null || { echo "$real"; return 0; }
  echo "$shim"
}

# 1. iris binary
IRIS="$(command -v iris || true)"
[ -z "$IRIS" ] && [ -x "$HOME/.local/bin/iris" ] && IRIS="$HOME/.local/bin/iris"
if [ -z "$IRIS" ]; then
  echo "MISSING: iris binary. Fix: bash scripts/install.sh"
  exit 1
fi
echo "iris: $("$IRIS" --version) ($IRIS)"

# 2. Chrome-family browser (explicit CHROME wins, then common installs)
CHROME="${CHROME:-}"
if [ -z "$CHROME" ]; then
  for c in google-chrome google-chrome-stable chromium chromium-browser \
           brave-browser microsoft-edge "$HOME/tools/chrome-linux64/chrome"; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -z "$p" ] && [ -x "$c" ] && p="$c"
    if [ -n "$p" ]; then CHROME="$p"; break; fi
  done
fi
if [ -z "$CHROME" ]; then
  echo "MISSING: Chrome-family browser (Chrome, Chromium, Edge, Brave). Fix: bash scripts/install.sh"
  exit 1
fi
CHROME="$(iris_chrome_for_iris "$CHROME")"
echo "chrome: $CHROME"

# 3. Smoke capture (the same one the README recommends)
OUT="$(mktemp -d)/iris-doctor.png"
if "$IRIS" https://example.com --selector h1 --padding 8 --scale 1 --json \
     -o "$OUT" --chrome "$CHROME" >/dev/null 2>&1; then
  size="$(wc -c < "$OUT" 2>/dev/null || echo 0)"
  if [ "${size:-0}" -gt 0 ]; then
    echo "smoke: OK ($size bytes)"
    echo "iris-doctor: READY"
    echo "CHROME_PATH=$CHROME"
    exit 0
  fi
fi
echo "smoke: FAILED — see the screenshot skill's references/troubleshooting.md"
exit 1
