#!/bin/sh
# iris installer — makes iris + a Chrome-family browser available.
# Idempotent: skips what is already present. Linux may need sudo for system libs.
set -eu

# sudo only when we are not already root and sudo exists
SUDO=""
if [ "$(id -u)" != "0" ] && command -v sudo >/dev/null 2>&1; then
  SUDO=sudo
fi

# Chrome refuses to run as root without --no-sandbox (crbug.com/638180) and iris
# has no flag to forward it, so wrap the binary in a shim and point iris there.
# Set IRIS_NO_SANDBOX_SHIM=0 to opt out.
iris_chrome_for_iris() {
  real="$1"
  [ "${IRIS_NO_SANDBOX_SHIM:-1}" = "1" ] || { echo "$real"; return 0; }
  [ "$(id -u)" = "0" ] || { echo "$real"; return 0; }
  case "$real" in *chrome-no-sandbox) echo "$real"; return 0 ;; esac
  shim="$HOME/tools/chrome-no-sandbox"
  mkdir -p "$HOME/tools" 2>/dev/null || { echo "$real"; return 0; }
  printf '#!/bin/sh\n# generated by the iris plugin: Chrome will not run as root without --no-sandbox\nexec "%s" --no-sandbox "$@"\n' "$real" > "$shim" 2>/dev/null || { echo "$real"; return 0; }
  chmod +x "$shim" 2>/dev/null || { echo "$real"; return 0; }
  echo "$shim"
}

# 1. iris binary (static prebuilt; no Rust needed)
if ! command -v iris >/dev/null 2>&1 && [ ! -x "$HOME/.local/bin/iris" ]; then
  echo "Installing iris (static binary → ~/.local/bin/iris)…"
  curl -fsSL https://raw.githubusercontent.com/brijr/iris/main/install.sh | sh
fi
IRIS="$(command -v iris || echo "$HOME/.local/bin/iris")"
echo "iris: $("$IRIS" --version) → $IRIS"
case ":$PATH:" in
  *":$HOME/.local/bin:"*) ;;
  *) echo "note: $HOME/.local/bin is not on PATH — add it to your shell profile" ;;
esac

# 2. Chrome-family browser: reuse an existing one if found
CHROME="${CHROME:-}"
if [ -z "$CHROME" ]; then
  for c in google-chrome google-chrome-stable chromium chromium-browser brave-browser microsoft-edge; do
    p="$(command -v "$c" 2>/dev/null || true)"
    if [ -n "$p" ]; then CHROME="$p"; break; fi
  done
fi

# 3. If none, install Chrome for Testing (Linux) or ask (elsewhere)
if [ -z "$CHROME" ]; then
  case "$(uname -s)" in
    Linux)
      DIR="$HOME/tools/chrome-linux64"
      if [ ! -x "$DIR/chrome" ]; then
        # Current Stable from Chrome for Testing, with a pinned fallback.
        VER="$(curl -fsSL --max-time 20 \
          https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json \
          2>/dev/null \
          | sed -n 's/.*"Stable":{[^}]*"version":"\([^"]*\)".*/\1/p')"
        [ -n "$VER" ] || VER="153.0.8010.47"
        echo "Installing Chrome for Testing $VER…"
        command -v unzip >/dev/null 2>&1 || $SUDO apt-get install -y -qq unzip
        mkdir -p "$DIR/.." && cd "$DIR/.."
        curl -fsSL -o chrome.zip "https://storage.googleapis.com/chrome-for-testing-public/$VER/linux64/chrome-linux64.zip"
        unzip -q -o chrome.zip && rm chrome.zip
        $SUDO apt-get update -qq
        $SUDO apt-get install -y -qq libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
          libatspi2.0-0 libcups2 libxkbcommon0 libxdamage1 fonts-liberation
        $SUDO apt-get install -y -qq libasound2t64 2>/dev/null \
          || $SUDO apt-get install -y -qq libasound2
        echo "note: export CHROME=\"$DIR/chrome\"   (or pass --chrome to iris)"
      fi
      CHROME="$DIR/chrome"
      ;;
    Darwin)
      echo "No Chrome-family browser found. Install Chrome/Chromium/Edge/Brave from your app store or vendor, then re-run doctor."
      exit 1
      ;;
    *)
      echo "Unsupported platform: $(uname -s). Install Chrome/Chromium/Edge and set CHROME=/path/to/browser."
      exit 1
      ;;
  esac
fi

CHROME="$(iris_chrome_for_iris "$CHROME")"
echo "chrome: $CHROME"
case "$CHROME" in
  *chrome-no-sandbox)
    echo "note: running as root — iris will use the --no-sandbox shim above" ;;
esac
echo "Done. Verify with: bash scripts/doctor.sh"
