#!/bin/sh
# iris-mcp.sh — bootstraps iris + a Chrome-family browser, then serves the
# iris MCP camera on stdio. All bootstrap noise goes to a log file so the
# stdio JSON-RPC stream stays clean.
set -u

LOG="${TMPDIR:-/tmp}/iris-mcp-bootstrap.log"
exec 3>"$LOG"   # fd 3 = bootstrap log

die() {
  echo "[iris-mcp] $1 (log: $LOG)" >&2
  exit 1
}

# Chrome refuses to run as root without --no-sandbox (crbug.com/638180) and iris
# has no flag to forward it, so wrap the binary in a shim and point iris there.
# Set IRIS_NO_SANDBOX_SHIM=0 to opt out.
iris_chrome_for_iris() {
  real="$1"
  [ "${IRIS_NO_SANDBOX_SHIM:-1}" = "1" ] || { echo "$real"; return 0; }
  [ "$(id -u)" = "0" ] || { echo "$real"; return 0; }
  case "$real" in *chrome-no-sandbox) echo "$real"; return 0 ;; esac
  shim="$HOME/tools/chrome-no-sandbox"
  mkdir -p "$HOME/tools" 2>/dev/null || { echo "$real"; return 0; }
  printf '#!/bin/sh\n# generated by the iris plugin: Chrome will not run as root without --no-sandbox\nexec "%s" --no-sandbox "$@"\n' "$real" > "$shim" 2>/dev/null || { echo "$real"; return 0; }
  chmod +x "$shim" 2>/dev/null || { echo "$real"; return 0; }
  echo "$shim"
}

# sudo only when we are not already root and sudo exists
SUDO=""
if [ "$(id -u)" != "0" ] && command -v sudo >/dev/null 2>&1; then
  SUDO=sudo
fi

IRIS="$(command -v iris || true)"
[ -z "$IRIS" ] && [ -x "$HOME/.local/bin/iris" ] && IRIS="$HOME/.local/bin/iris"
if [ -z "$IRIS" ]; then
  echo "[iris-mcp] installing iris…" >&2
  curl -fsSL https://raw.githubusercontent.com/brijr/iris/main/install.sh | sh >&3 2>&1 \
    || die "iris install failed"
  IRIS="$HOME/.local/bin/iris"
  [ -x "$IRIS" ] || die "iris install did not produce $IRIS"
fi

CHROME="${CHROME:-}"
if [ -z "$CHROME" ]; then
  for c in google-chrome google-chrome-stable chromium chromium-browser \
           brave-browser microsoft-edge "$HOME/tools/chrome-linux64/chrome"; do
    p="$(command -v "$c" 2>/dev/null || true)"
    [ -z "$p" ] && [ -x "$c" ] && p="$c"
    if [ -n "$p" ]; then CHROME="$p"; break; fi
  done
fi

if [ -z "$CHROME" ]; then
  case "$(uname -s)" in
    Linux)
      DIR="$HOME/tools/chrome-linux64"
      if [ ! -x "$DIR/chrome" ]; then
        echo "[iris-mcp] installing Chrome for Testing…" >&2
        # Current Stable from Chrome for Testing, with a pinned fallback.
        VER="$(curl -fsSL --max-time 20 \
          https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions.json \
          2>/dev/null \
          | sed -n 's/.*"Stable":{[^}]*"version":"\([^"]*\)".*/\1/p')"
        [ -n "$VER" ] || VER="153.0.8010.47"
        (
          set -e
          command -v unzip >/dev/null 2>&1 || $SUDO apt-get install -y -qq unzip
          mkdir -p "$DIR/.."
          cd "$DIR/.."
          curl -fsSL -o chrome.zip \
            "https://storage.googleapis.com/chrome-for-testing-public/$VER/linux64/chrome-linux64.zip"
          unzip -q -o chrome.zip
          rm chrome.zip
          $SUDO apt-get update -qq
          $SUDO apt-get install -y -qq libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 \
            libatspi2.0-0 libcups2 libxkbcommon0 libxdamage1 fonts-liberation
          $SUDO apt-get install -y -qq libasound2t64 2>/dev/null \
            || $SUDO apt-get install -y -qq libasound2
        ) >&3 2>&1 || die "Chrome for Testing $VER install failed"
      fi
      CHROME="$DIR/chrome"
      ;;
    *)
      die "no Chrome-family browser found; install one or set CHROME"
      ;;
  esac
fi

[ -x "$CHROME" ] || die "Chrome binary is not executable: $CHROME"
CHROME="$(iris_chrome_for_iris "$CHROME")"

echo "[iris-mcp] ready: iris=$IRIS chrome=$CHROME (log: $LOG)" >&2
exec "$IRIS" mcp --chrome "$CHROME"
